twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/assets/images': images
        '%kernel.project_dir%/public/assets/css': css
    globals:
        societyName: Garanties Optimales
        statusSociety : SARL MGL Courtage
        emailSociety : mglcourtage7@gmail.com