vich_uploader:
  db_driver: orm
  mappings:
    document_fichier:
      uri_prefix:         /assets/images/attachment/tmp
      upload_destination: '%kernel.project_dir%/public/assets/images/attachment/tmp'
      #delete_on_remove: true
      #delete_on_update: true